name: Build and Release DRS

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Set up GCC (Linux)
      if: matrix.os == 'ubuntu-latest'
      uses: egor-tensin/setup-gcc@v1
      with:
        version: latest
        platform: x64

    - name: Build DRS (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        gcc -o drs drs.c -lpthread
        tar -czvf drs-${{ matrix.os }}.tar.gz drs

    - name: Build DRS (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        clang -o drs drs.c -lpthread
        tar -czvf drs-${{ matrix.os }}.tar.gz drs

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          drs-${{ matrix.os }}.tar.gz
